"""Write lookup_icon_data.py from assets/lookup_icons/*.png"""
from __future__ import annotations

import base64
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ICONS = ROOT / "assets" / "lookup_icons"
ORDER = ("tag", "layers", "clock", "person", "grid")


def main() -> None:
    lines = [
        "# Auto-generated by tools/generate_lookup_icons.py; do not edit by hand.",
        "_LK_ICO_PNG_B64: dict[str, str] = {",
    ]
    for k in ORDER:
        p = ICONS / f"{k}.png"
        b64 = base64.standard_b64encode(p.read_bytes()).decode("ascii")
        lines.append(f'    "{k}": "{b64}",')
    lines.append("}")
    out = ROOT / "lookup_icon_data.py"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("Wrote", out)


if __name__ == "__main__":
    main()
